AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  CloudFormation template to create an EC2 instance with dynamic AMI selection
  based on the AWS region. This template uses Mappings to select the correct AMI
  and Conditions to control resource creation based on the environment type.

Parameters:
  InstanceType:
    Description: Type of EC2 instance to launch.
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - m5.large
      - m5.xlarge
    ConstraintDescription: Must be a valid EC2 instance type.

  KeyName:
    Description: Name of an existing EC2 key pair to enable SSH access.
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing EC2 key pair.

  SSHLocation:
    Description: The IP address range that can SSH into the EC2 instance.
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: Must be a valid IP CIDR range.

  EnvironmentType:
    Description: The type of environment (e.g., prod, dev).
    Type: String
    Default: dev
    AllowedValues:
      - prod
      - dev
    ConstraintDescription: Must be either "prod" or "dev".

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0e1bed4f06a3b463d  # Replace with a valid AMI ID for us-east-1.
    us-west-2:
      AMI: ami-0606dd43116f5ed57 # Replace with a valid AMI ID for us-west-2.
    eu-west-1:
      AMI: ami-032a56ad5e480189c # Replace with a valid AMI ID for eu-west-1.
    ap-south-1:
      AMI: ami-08a218fd6813ab90b # # Replace with a valid AMI ID for us-east-1-1.

Conditions:
  CreateProdResources: !Equals [!Ref EnvironmentType, "prod"]

Transform: AWS::Serverless-2016-10-31

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI] # Dynamically select AMI based on region.
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: !If [CreateProdResources, "ProdInstance", "DevInstance"]

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation

  ProdOnlyResource:
    Type: AWS::SNS::Topic
    Condition: CreateProdResources
    Properties:
      TopicName: ProdTopic

Outputs:
  InstanceId:
    Description: Instance ID of the newly created EC2 instance.
    Value: !Ref EC2Instance

  PublicIP:
    Description: Public IP address of the EC2 instance.
    Value: !GetAtt EC2Instance.PublicIp

  SecurityGroupId:
    Description: Security group ID associated with the EC2 instance.
    Value: !Ref InstanceSecurityGroup

  AMIUsed:
    Description: The AMI ID used for the EC2 instance.
    Value: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]

  ProdTopicArn:
    Description: ARN of the SNS topic created in production environment.
    Value: !If [CreateProdResources, !Ref ProdOnlyResource, "No SNS topic created (not in production)."]
