version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html

hooks:
  ApplicationStop:
    - location: scripts/clean_apache.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/install_apache.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/restart_apache.sh
      timeout: 300
      runas: root
