AWSTemplateFormatVersion: '2010-09-09'
Description: Simple EC2 Instance

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    Description: EC2 instance type.

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-0c4b8d05558aa0e8d  # Change based on your AWS region
      Tags:
        - Key: Name
          Value: MyTestInstance
