apiVersion: v1
kind: Service
metadata:
  name: desh-service
  namespace: desh-app
spec:
  type: LoadBalancer
  selector:
    app: desh-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
