AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Simplified CloudFormation template to create an EC2 instance with a CreationPolicy.

Parameters:
  InstanceType:
    Description: Type of EC2 instance to launch.
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    ConstraintDescription: Must be a valid EC2 instance type.

  KeyName:
    Description: Name of an existing EC2 key pair to enable SSH access.
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing EC2 key pair.

  SSHLocation:
    Description: The IP address range that can SSH into the EC2 instance.
    Type: String
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: Must be a valid IP CIDR range (e.g., 192.168.0.0/16).

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-0e1bed4f06a3b463d # Replace with a valid AMI ID for your region.
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Install the AWS CloudFormation helper scripts
          apt-get update
          apt-get install -y python3-pip
          pip3 install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-py3-latest.tar.gz
          
          # Intentional failure: Sleep for 10 minutes (600 seconds), which is longer than the 5-minute timeout, thus the CF fails
          sleep 600
          
          # Signal CloudFormation that the instance is ready
          /usr/local/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource EC2Instance --region ${AWS::Region}
    CreationPolicy:
      ResourceSignal:
        Timeout: PT5M # Wait for 5 minutes for the signal
        Count: 1      # Wait for 1 success signal

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation

Outputs:
  InstanceId:
    Description: Instance ID of the newly created EC2 instance.
    Value: !Ref EC2Instance

  PublicIP:
    Description: Public IP address of the EC2 instance.
    Value: !GetAtt EC2Instance.PublicIp
